schema: http://127.0.0.1:8000/graphql
documents: ./src/**/*.graphql
generates:
  ./src/app/types/types.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-apollo-angular