pub mod user;
pub mod usertypes;
pub mod employee;
pub mod manager;
pub mod credentials;
pub mod personalinformation;
pub mod contact;
pub mod userid;
pub mod available_laguages;
pub mod authentication;
mod tests;