/*Posgresql database*/

DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS RECIPIES;
DROP TABLE IF EXISTS META;

DROP TABLE IF EXISTS 
CREATE TABLE IF NOT EXISTS USERS (
    id uuid NOT NULL,
    username VARCHAR(255) NOT NULL,
    password text NOT NULL,
    email VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS RECIPIES (
    id uuid NOT NULL,
    recipie TEXT NOT NULL
);

Create TABLE IF NOT EXISTS META (
    create_date TIMESTAMP
    edit_date TIMESTAMP
);