GET http://127.0.0.1:8000/diesel/

### Create post

POST http://127.0.0.1:8000/diesel/
Content-Type: application/json

{
    "title": "Something",
    "text": "Something deeper than me"
}

### Get post with id

GET http://127.0.0.1:8000/diesel/1



### Get all users
GET http://127.0.0.1:8000/diesel/users

###  Create user
POST http://127.0.0.1:8000/diesel/user
Content-Type: application/json

{
    "name": "something",
    "email": "123@123.com",
    "password": "123"
}

### User login
POST http://127.0.0.1:8000/diesel/login
Content-Type: application/json

{
    "email": "123@123.com",
    "password": "123"
}

### Example to check token info
GET http://127.0.0.1:8000/diesel/tokenexample
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NjQxMjY2MjksImV4cCI6MTY2NDEzNzQyOSwidXNlciI6eyJpZCI6MiwiZW1haWwiOiIxMjNAMTIzLmNvbSIsInJvbGUiOiJVc2VyIn19.6Cm6DMXQDYz8kslO-7pUO1FY-fWpYMDj8uxDnN8hUX0



