GET http://127.0.0.1:8000/diesel/

### Create post

POST http://127.0.0.1:8000/diesel/
Content-Type: application/json

{
    "title": "Something",
    "text": "Something deeper than me"
}

### Get post with id

GET http://127.0.0.1:8000/diesel/1



### Get all users
GET http://127.0.0.1:8000/diesel/users

###  Create user
POST http://127.0.0.1:8000/diesel/user
Content-Type: application/json

{
    "name": "something",
    "email": "c@a.com",
    "password": "123"
}